### ISSUE TITLE
Proposta pra tradução do documento pra pt-BR

### ISSUE THREAD

**Issue by felipesousa** [bpassos/git-commands#11]
Opa! Bruno eu gostei bastante desse seu repo, principalmente porque ele vai de forma bem direta e funcional. Andei mostrando seu repo pra alguns amigos e eles alegaram não adquirir seu repo por conta que está em inglês coisa e tal.. ( o que pra mim não foi problema ) porém, pensando nisso e tentando fazer com que suas anotações chegue o mais pessoas e possa as ajudar também, estou me propondo a fazer a tradução do documento caso aceite. Dai eu poderia subir e mandar por outro branch e tudo mais.. Tem algum problema ou tudo bem em eu traduzir e mandar ? Abraço!

**Comment by bpassos** [comment]
Opa Felipe!

Que bom que achas o documento útil e valeu por mostrar a outras pessoas. 

Então, traduzir pra mim não seria um problema. O que vem a cabeça são os seguintes pontos:

1- a tradução ficaria na mesma página? Se sim eu me preocupo com o tamanho final da página. O que poderíamos fazer é criar um outro repo é linkar de um para o outro.

Como vc pensou em fazer isso?

Quanto aos colegas que não sabem inglês, eu incentivaria tentar aprender via documentos sobre desenvolvimento como este. Inglês é super importante especialmente pra o que nós fazermos.

Fico ao aguardo de um resposta.

Abraço,

Bruno

**Comment by michelamaral** [comment]
Olá Pessoal, bom dia!
Concordo com o Bruno que Inglês é super importante e as pessoas deveriam
aprender. Mas também concordo que pessoas que não sabem inglês deveriam ter
acesso ao conteúdo.

Então deixando de lado saber ou não inglês, porque não facilitar para quem
não sabe?

Segue minha opinião/sugestão:
- Traduzir para português.
- Voluntários ajudar na tradução.
- Na minha opinião da para usar o mesmo repositório, apenas criar pastas
especificas para o conteúdo em cada língua: pt-BR, EN, etc, etc...

OBS: fiquem a vontade para complementar, discordar ou trazer novas
sugestões para dar um "merge" :)

Estou disposto a ajudar tbm! ;)

Atenciosamente,

Michel Amaral
www.designa.com.br






Em dom, 21 de jun de 2015 às 02:51, Bruno Passos <notifications@github.com>
escreveu:

**Comment by ciceropablo** [comment]
Acho importante a tradução e voto por ela. O modelo sugerido pelo @michelamaral é interessante por manter tudo no mesmo repositório. Voto por este também.

**Comment by felipesousa** [comment]
Show! A minha ideia era fazer arquivos .md para cada tradução.. Porém o lance das pastas fica mais organizado. Irado! :D

**Comment by bpassos** [comment]
Fala galera! Bom, eu sigo a maioria! Simbora!

**Comment by bpassos** [comment]
Então, acho que a proposta do @michelamaral e boa! vamos criar uma branch remota e começar a tradução?

Quem se disponibiliza a ajudar a traduzir?

Abraco!

**Comment by ramonvictor** [comment]
Meus 2 cents:

Acho válida a ideia de tradução e também concordo com manter tudo no mesmo repositório.
Em termos de estrutura, acho que deveríamos manter o inglês como o README.md principal e criar uma pasta "translation", ou algum nome melhor, para colocar as versões traduzidas, exemplo: `translation/README.pt-br.md`.

Bem no início do README em inglês, colocaríamos uma navegação para as traduções, exemplo: **en / [pt-br](translation/README.pt-br.md)**.

**Comment by bpassos** [comment]
Boa @ramonvictor acho que essa e a melhor forma de fazer isso!
